spring:
  application:
    name: gymload-api

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

  aws:
    accessKeyId: 0053827d213c74a0000000001
    secretKey: K005fxgktfYLGYGLLOkHDtEkP/N1vo4
    region: us-east-005
    bucket:
      name: gymload
    endpoint: https://s3.us-east-005.backblazeb2.com
