-- Dados iniciais Grupo Muscular
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (1, 'Peitoral', 'PEITORAL');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (2, 'Biceps', 'BICEPS');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (3, 'Triceps', 'TRICEPS');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (4, 'Costas', 'COSTAS');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (5, 'Ombro', 'OMBRO');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (6, 'Antebraço', 'ANTEBRACO');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (7, 'Abdomen', 'ABDOMEN');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (8, 'Quadriceps', 'QUADRICEPS');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (9, 'Panturrilha', 'PANTURRILHA');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (10, 'Posterior de Coxa', 'POSTERIOR_COXA');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (11, 'Cardio', 'CARDIO');








