-- USUARIOS
INSERT INTO USUARIO (ID, UUID, NOME, USERNAME, SENHA, EMAIL) VALUES (1, 'c2d83d78-e1b2-4f7f-b79d-1b83f3c435f9', 'USUARIO ADMIN', 'USUARIO_ADMIN', '$2a$10$QByEoLAMS4JYufIFuQDke.Qvn8PSrwJzxMywB.h/90pq7Zq1JSboK', 'testeAdmin@teste.com');

-- USUARIOS_ROLES
INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLE) VALUES (1, 'ADMIN');
INSERT INTO USUARIO_ROLE (USUARIO_ID, ROLE) VALUES (1, 'USER');

-- GRUPOS MUSCULARES
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (1, 'Peitoral', 'PEIROTAL');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (2, 'Costas', 'COSTAS');
INSERT INTO GRUPO_MUSCULAR (ID, NOME, CODIGO) VALUES (3, 'Abdomen', 'ABDOMEN');

-- EXERCICIOS
INSERT INTO EXERCICIO (ID, NOME, DESCRICAO, TIPO_EQUIPAMENTO, TIPO_EXERCICIO, TIPO_PEGADA, FK_GRUPO_MUSCULAR) VALUES (1, 'SUPINO RETO', 'Supino Reto', 'HALTER', 'MUSCULACAO', 'PRONADA', 1);
INSERT INTO EXERCICIO (ID, NOME, DESCRICAO, TIPO_EQUIPAMENTO, TIPO_EXERCICIO, TIPO_PEGADA, FK_GRUPO_MUSCULAR) VALUES (2, 'PUXADA ALTA', 'Puxada Alta', 'MAQUINA', 'MUSCULACAO', 'PRONADA', 2);
INSERT INTO EXERCICIO (ID, NOME, DESCRICAO, TIPO_EXERCICIO, FK_GRUPO_MUSCULAR) VALUES (3, 'ABDOMINAL SUPRA', 'Abdominal Supra', 'CALISTENIA', 3);

-- TREINOS
INSERT INTO TREINO (ID, NOME, DATA_CADASTRO, FK_USUARIO, SITUACAO) VALUES (1, 'TREINO 1', '2025-03-04', 1, 'ATIVO');

-- TREINOS_EXERCICIOS
INSERT INTO TREINO_EXERCICIO (FK_TREINO, FK_EXERCICIO, ORDEM_EXERCICIO) VALUES (1, 1, 0);

-- REGISTRO_MUSCULACAO
INSERT INTO REGISTRO_MUSCULACAO (ID, PESO, UNIDADE_PESO, QTD_REPETICOES, DATA_CADASTRO, QTD_SERIES, FK_EXERCICIO, FK_USUARIO) VALUES (1, 22.5, 'KG', 12, '2025-03-04', 4, 1, 1);
INSERT INTO REGISTRO_MUSCULACAO (ID, PESO, UNIDADE_PESO, QTD_REPETICOES, DATA_CADASTRO, QTD_SERIES, FK_EXERCICIO, FK_USUARIO) VALUES (2, 25.0, 'KG', 8, '2025-03-14', 3, 1, 1);

-- REGISTRO_AEROBICO
INSERT INTO REGISTRO_AEROBICO (ID, DURACAO, DISTANCIA, DATA_CADASTRO, FK_EXERCICIO, FK_USUARIO) VALUES (1, 22.5, 1.5,  '2025-03-04', 2, 1);
INSERT INTO REGISTRO_AEROBICO (ID, DURACAO, DISTANCIA, DATA_CADASTRO, FK_EXERCICIO, FK_USUARIO) VALUES (2, 20.0, 2.5,  '2025-03-14', 2, 1);

-- REGISTRO_CALISTENIA
INSERT INTO REGISTRO_CALISTENIA (ID, QTD_SERIES, QTD_REPETICOES, DATA_CADASTRO, FK_EXERCICIO, FK_USUARIO) VALUES (1, 5, 30,  '2025-03-04', 3, 1);
INSERT INTO REGISTRO_CALISTENIA (ID, PESO_ADICIONAL, UNIDADE_PESO, QTD_SERIES, QTD_REPETICOES, DATA_CADASTRO, FK_EXERCICIO, FK_USUARIO) VALUES (2, 10, 'KG', 4, 50,  '2025-03-14', 3, 1);
